POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento teste",
  "details": "testando evento",
  "maximumAttendees": 10
}

###

POST http://localhost:3333/events/d557bcdd-eb47-4211-b1d2-2d486d3b8838/attendees
Content-Type: application/json

{
  "name": "Cleonan Brito",
  "email": "cleonan7@bol.com.br"
}

###

GET http://localhost:3333/events/d557bcdd-eb47-4211-b1d2-2d486d3b8838

###
GET http://localhost:3333/attendees/7/badge

###
GET http://localhost:3333/attendees/7/check-in

###
GET http://localhost:3333/events/d557bcdd-eb47-4211-b1d2-2d486d3b8838/attendees?query=cl
